db:
  configurations:
    0:
      url: jdbc:mysql://localhost:3306/aion?useSSL=false&serverTimezone=CET
      username: root
      driver: com.mysql.cj.jdbc.Driver
      password:
    1:
      url: jdbc:mysql://localhost:3306/aion_c?useSSL=false&serverTimezone=CET
      username: root
      driver: com.mysql.cj.jdbc.Driver
      password:
    2:
      url: jdbc:mysql://localhost:3306/aion_eu?useSSL=false&serverTimezone=CET
      username: root
      driver: com.mysql.cj.jdbc.Driver
      password: